fattmerchantorg/fattmerchant-android-sdk

cardpresent/src/main/java/com/fattmerchant/android/InitParams.kt
cardpresent/src/main/java/com/fattmerchant/android/Omni.kt
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaUtils.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/TransactionRequest.kt
cardpresent/src/test/java/com/fattmerchant/omni/chipdna/ChipDnaUtilsTest.kt
cardpresent/src/test/java/com/fattmerchant/omni/data/TransactionRequestTests.kt

NMI has the ability to tokenize a payment method using the card readers. As Fattmerchant, we want to be able to offer that functionality to the users of our SDK
- Added `tokenize` field to `TransactionRequest`
- added `appId` to `InitParams` because it was missing

PHX-125 Request CustomerVault Token

---

cardpresent/src/main/java/com/fattmerchant/android/InitParams.kt
cardpresent/src/main/java/com/fattmerchant/android/Omni.kt
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaUtils.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/TransactionRequest.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/TransactionResult.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/models/PaymentMethod.kt
cardpresent/src/main/java/com/fattmerchant/omni/networking/OmniApi.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakeMobileReaderPayment.kt
cardpresent/src/test/java/com/fattmerchant/omni/chipdna/ChipDnaUtilsTest.kt
cardpresent/src/test/java/com/fattmerchant/omni/data/TransactionRequestTests.kt

We can now get the token for the payment method from NMI, so now we need that stored in Omni so we can use that payment method from other Omni products. This specific feature covers the injection of the token into Omni
- Modified the `TransactionResult`, and `PaymentMethod` objects to be aware of `paymentToken`
- Made `ChipDnaDriver` pass the `paymentToken` to the `TransactionResult`
- Made `TakeMobileReaderPaymentTransaction` use the `/payment-method/token` route, which stores the token along with the payment method

PHX-127 Store tokenized payment method in Omni

---

cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/TransactionResult.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakeMobileReaderPayment.kt
cardpresent/src/test/java/com/fattmerchant/omni/usecase/TakeMobileReaderPaymentTest.kt

In order to do linkedRefunds from Omni Gateway, we need to be able to reference a transaction by the id that NMI will recognize
* Started recording the transaction id that NMI gives us in a TransactionResult.externalId
* started recording the CardEaseReference to TransactionResult.localId
* Added documentation explaining what they both are

PHX-128 Store transaction id for future linkedRefunds

---

cardpresent/src/main/java/com/fattmerchant/omni/data/models/Transaction.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakeMobileReaderPayment.kt

In order for Omni to be be able to refund a transaction done using the CPSDK, we need to tell Omni the id of that transaction. Omni will require that we pass this in as a token when we POST the transaction.
Added the token field to the Transaction model
Made ChipDna transactions put the token in the Transaction model

[PHX-401] Add transaction token to transactions

---

cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaUtils.kt
cardpresent/src/main/java/com/fattmerchant/omni/MobileReaderConnectionStatusListener.kt
cardpresent/src/main/java/com/fattmerchant/omni/Omni.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/MobileReaderDriver.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/models/MobileReaderConnectionStatus.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/ConnectMobileReader.kt

When connecting to a mobile reader, there is no idea of what is happening from the moment that you call omni.connect(reader:completion:error:) to the moment that you hit the completion or the error block. However, the mobile reader is typically doing a ton of work during this time. Work that includes:
- Actually connecting the BT reader
- Making sure the BT reader can be used on behalf of the merchant
- Maybe doing a firmware update
- Maybe doing a TMS update
- Maybe rebooting
- Etc.
Another big problem is not knowing when a mobile reader disconnects by itself. If a mobile reader dies or is idle for too long, then it might disconnect itself from the iOS device. But prior to this PR, there is no way to listen for the disconnect event to allow the user to reconnect the mobile reader.
I …

[MOB-1] Show Mobile Reader Connection Status

---

cardpresent/src/main/java/com/fattmerchant/omni/usecase/ConnectMobileReader.kt

Need to add mobileReaderConnectionStatusListener in ConnectMobileReader else block.

[SPRINT-142][MOB-32] Add mobileReaderConnectionStatusListener to driver

---

cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt
cardpresent/src/main/java/com/fattmerchant/omni/Omni.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/models/MobileReaderDetails.kt
cardpresent/src/main/java/com/fattmerchant/omni/networking/OmniApi.kt

We are now getting the mobile reader settings from a new route: team/gateway/hardware/mobile instead of passing along that data from the merchant object.
Instead of passing the merchant object along to the drivers, I pass the retrieved mobile reader details. This is the same for both NMI and AWC readers.

[SPRINT-143] [MOB-61] Get mobile reader settings from new route in gateway

---

cardpresent/src/main/java/com/fattmerchant/omni/data/TransactionRequest.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/models/CatalogItem.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakeMobileReaderPayment.kt
cardpresent/src/test/java/com/fattmerchant/omni/usecase/InitializeDriversTest.kt
cardpresent/src/test/java/com/fattmerchant/omni/usecase/TakeMobileReaderPaymentTest.kt

This adds support in the SDK for the ability to provide a list of catalog items to a transaction request. It uses the `meta` field in the `TransactionRequest` to pass to the Omni API.
Added a new model object called `CatalogItem` which maps the object passed to the `meta` field.
Added `lineItems` list to the `TransactionRequest` and created a public constructor to support the new field.
Added a new dictionary item to the meta data being passed in the use case of `TakeMobileReaderPayment` that contains the encoded line items.
Wrote a test case to validate the metadata is properly formed in the `TransactionRequest`.

[SPRINT-144][MOB-70] Support catalog items

---

cardpresent/src/main/java/com/fattmerchant/android/anywherecommerce/AWCDriver.kt
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt
cardpresent/src/main/java/com/fattmerchant/omni/Omni.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/MobileReaderDriver.kt
cardpresent/src/main/java/com/fattmerchant/omni/networking/OmniApi.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/RefundMobileReaderTransaction.kt

This adds support in the SDK for the ability to refund through the Omni API when the driver allows for it. For instance when we post a refund from NMI.
Added a method to `OmniApi` called `postVoidOrRefund` which handles the post for refund or void through the api.
Added a bool called `isOmniRefundsSupported` to `MobileReaderDriver` (NMI is **true** and AWC is **false** by default).
In the `RefundMobileReaderTransaction` use case I added a check to see if we are able to do an Omni refund. If so we post a request to the api. If not we call to the third party refund method.

[SPRINT-144][MOB-4] Support refunds across CP SDK devices

---

cardpresent/build.gradle
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt

When trying to connect to an NMI mobile reader that is paired but powered off, the SDK was not invoking the success or the fail callbacks. This left the consuming application in an infinite waiting state.
There was a bug in the way that we were throwing the exception. We were calling throw within a sub coroutine, and the parent coroutine was not rethrowing. I called the proper method, `cancellableContinuation.resumeWithException(Exception)` as per this doc https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-cancellable-continuation/#

[MOB-114] Connect reader not timing out and throwing error

---

cardpresent/src/main/java/com/fattmerchant/omni/data/models/Invoice.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/models/Transaction.kt

[MOB-122 pass in "channel": "android" on invoice and transaction POST/PUT](https://fattmerchant.atlassian.net/browse/MOB-122)
Transaction did not have field `channel`
• Added channel field to Transaction model

[MOB-122] pass in "channel": "android" on transaction POST/PUT

---

cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakeMobileReaderPayment.kt

[MOB-167 AWC Transaction should be marked not refundable](https://fattmerchant.atlassian.net/browse/MOB-167)
Trying to refund in VT leads to error "Error with refund. Unable to find the specified reference transaction."
AWC refunds will not work in the VT. In order to enable this functionality, we’d have to build the void/refund logic specific to AWC in Omni Gateway the same way we built it for NMI. Since we don’t want to do that, we want to mark the AWC transactions as not_refundable or something like that so that the VT/API does not attempt the refund. 
If our source reader is AWC then always return false for isRefundable and isVoidable

[MOB-167] AWC Transaction should be marked not refundable

---

cardpresent/src/main/java/com/fattmerchant/android/anywherecommerce/AWCDriver.kt

Fixes this crash:
https://console.firebase.google.com/u/0/project/omni-payments-and-analytics/crashlytics/app/android:com.fattmerchant.fattpay/issues/356c6ce48c7928ba368288517f0d87cc?time=last-twenty-four-hours&versions=1.7.0%20(58);1.7.0%20(56);1.7.0%20(55);1.7.0%20(54);1.7.0%20(53)&sessionEventKey=5FA9B9C001AB00015389E8B6651FDF1C_1471691953883006911

Safely wrap disconnect call to ensure card reader is not null

---

app/src/main/java/com/fattmerchant/fmsampleclient/MainActivity.kt
app/src/main/res/layout/activity_main.xml
cardpresent/src/main/java/com/fattmerchant/omni/Omni.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/TransactionRequest.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/models/BankAccount.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/models/ChargeRequest.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/models/CreditCard.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/models/PaymentMethod.kt
cardpresent/src/main/java/com/fattmerchant/omni/networking/OmniApi.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakePayment.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/TokenizePaymentMethod.kt

[MOB-340 Android SDK | The Android SDK needs to use /payment-method instead of /webpayments to tokenize](https://fattmerchant.atlassian.net/browse/MOB-340)
The Android SDK currently uses POST /webpayments/{hostedpaymentstoken}/tokenize in order to tokenize a payment method. This flow is not supported and we need to start using POST /payment-method
- Added use cases for TakePayment and TokenizePaymentMethod
- Added `pay` method to Omni.kt to take a `TransactionRequest` and charge it
- Added test case to sample app for taking a payment without reader

[MOB-340] Use /payment-method instead of /webpayments to tokenize

---

cardpresent/src/androidTest/java/com/fattmerchant/cpresent/InitializeDriversTest.kt
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/InitializeDrivers.kt

> **Android SDK | If there are no mobile reader settings, the sdk crashes**
* Changed the `InitializeDrivers` functionality to wrap each driver's `initialize` call with a try...catch. What was happening here was that the whole [getDrivers().map().blah()](https://github.com/fattmerchantorg/fattmerchant-android-sdk/compare/release/1.2.2...feature/MOB-468-initialization-crash?expand=1#diff-0300444504bc7b8a102610564bd10fde6a663d375272f3fcefd56342c317dd15L20-L25) was being wrapped in the try...catch, and idk if it has something to do with those being suspend functions, but the throwing exceptions were not being caught by the surrounding try...catch. 
* Updated the error message of the ChipDnaDriver to accurately represent the _actual_ error. This is going to let users receive the `detail` that …

[SPRINT-165][MOB-468] Android SDK | If there are no mobile reader settings, the sdk crashes

---

cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaUtils.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/models/MobileReaderConnectionStatus.kt

> **Android SDK | NMI bbPOS | Getting latest settings**
* Added flags for TMS and Firmware updates
* Combined `Registering` status with `Connecting`
---
---

[SPRINT-171][MOB-564] Added flags for TMS and Firmware updates

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/fattmerchant/fmsampleclient/MainActivity.kt
cardpresent/src/main/java/com/fattmerchant/android/anywherecommerce/AWCDriver.kt
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaTransactionListener.kt
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaUtils.kt
cardpresent/src/main/java/com/fattmerchant/omni/Omni.kt
cardpresent/src/main/java/com/fattmerchant/omni/UserNotificationListener.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/MobileReaderDriver.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/UserNotification.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakeMobileReaderPayment.kt
cardpresent/src/test/java/com/fattmerchant/omni/chipdna/ChipDnaUtilsTest.kt

> **Android SDK | NMI bbPOS | On screen prompts**
* Created a `UserNotification` object to map user notification response from ChipDNA to readable type
* Create a `UserNotificationListener` which is used to respond to the callbacks from ChipDNA user notifications
* Passed `UserNotificationListener` to `TakeMobileReaderPayment` usecase
---
---

[SPRINT-171][MOB-562] Provide UserNotificationListener to SDK

---

cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaUtils.kt
cardpresent/src/main/java/com/fattmerchant/omni/Omni.kt

> **Android SDK | Create a suspendable version of connect reader and pass back DISCONNECTED and CONNECTED statuses**
* Created a suspendable version of connectReader function that allows us to use it directly in a background work manager managed with coroutine scope.
* Pass back statuses for CONNECTED and DISCONNECTED that were previously not firing
---

[SPRINT-172][MOB-625] Suspendable connectReader

---

cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/TransactionResult.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakeMobileReaderPayment.kt

> **Android SDK | ChipDNA | Customer name for Apple Pay transaction is "SWIPE CUSTOMER"**
* Added new field to `TransactionResult` called `isFromMobileDevice`
* After mobile reader payment is completed check to see if there is a CCParamPar value which determines if the transaction has a device PAN.
* When creating a new customer check to see if the transaction `isFromMobileDevice` and set the name to "Mobile Device Customer"
---

[SPRINT-172][MOB-613] ApplePay Customer Name

---

cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakeMobileReaderPayment.kt

> **Android SDK 2.0.0 | Customer name for Apple Pay transaction should be "Mobile Device Customer" instead of "Contactless Customer"**
* Changed "Contactless Customer" to "Mobile Device Customer"
---

[SPRINT-180][MOB-748] Change "Contactless Customer" to "Mobile Device Customer"

---

cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakeMobileReaderPayment.kt

> **Android SDK 2.0.0 | Taking a payment with an invoice of "" will show as successful in transactiongateway but will not show up at all in Stax**
* Added a check before continuing with the transaction if the invoice id has any blank characters.
---
---

[SPRINT-180][MOB-743] Throw exception when invoice id is blank

---

cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaUtils.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/MobileReaderDriver.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakeMobileReaderPayment.kt

> **ANDROID SDK -[EFS][EPS][NMI][AWC][BBPOS] Transactions not getting created initially when ran on mobile reader**
* Make transactions not get autoconfirmed by NMI
* Wrap each transaction with auth+capture such that the transaction doesn't _actually_ get captured until Stax has all the necessary records created
Note that this is the same change we did for iOS SDK 
---

[SPRINT-185][MOB-779] Wrap transactions with auth + cap

---

cardpresent/src/main/java/com/fattmerchant/omni/Omni.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakeMobileReaderPayment.kt

> **Android SDK 2.1.2 | Tip not showing up in Stax**
* Include additional fields in invoice meta
---

[SPRINT-188][MOB-836] Include meta in invoice

---

cardpresent/src/main/java/com/fattmerchant/android/anywherecommerce/AWCDriver.kt

> **Android 2.1.1 | AWC crash on initialize**
* Prevented invocations of AWC methods if AWC creds not provided

[SPRINT-190] [MOB-859] Fix AWC crash

---

cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/repository/TransactionRepository.kt
cardpresent/src/main/java/com/fattmerchant/omni/networking/OmniApi.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakeMobileReaderPayment.kt

> **Unable to perform sale**
* Changed the key of one of the values we were expecting from ChipDNA from RESULT -> TRANSACTION_RESULT
* Made the SDK update Stax if a capture failed

[SPRINT-190][MOB-832] Unable to perform sale

---

cardpresent/src/main/java/com/fattmerchant/omni/data/TransactionRequest.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/TakeMobileReaderPayment.kt

> **Android SDK 2.2.0 | Add shipping amount and po number to TransactionRequest**
* Added `shippingAmount` and `poNumber` to TransactionRequest
---

[SPRINT-197][MOB-959] Add shippingAmount and poNumber to TransactionRequest

---

cardpresent/src/main/AndroidManifest.xml
cardpresent/src/main/java/com/fattmerchant/android/anywherecommerce/AWCDriver.kt
cardpresent/src/main/java/com/fattmerchant/android/dejavoo/DejavooDriver.kt
cardpresent/src/main/java/com/fattmerchant/android/dejavoo/DejavooDriverUtils.kt
cardpresent/src/main/java/com/fattmerchant/omni/Omni.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/TransactionRequest.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/models/Merchant.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/models/PaymentType.kt
cardpresent/src/main/java/com/fattmerchant/omni/data/models/Terminal.kt
cardpresent/src/main/java/com/fattmerchant/omni/usecase/InitializeDrivers.kt

> **Android SDK | Crash on SDKManager**
* Enabled AnyWhereCommerce service/terminated; because it gets killed when on background`onDestory` as of Firebase's report
*  Added additional guard condition during disconnection
---

[SPRINT-223] [MOB-1188] Crash on SDK manager

---

cardpresent/src/main/java/com/fattmerchant/android/dejavoo/DejavooDriver.kt

> **Fix Refund/Void bug for Dejavoo**
We use Dejavoo's DejaPay SDK in order to send payment intents to Dejavoo's payment app, Aura. Our integration of DejaPay works perfectly fine on Engineering Mode terminals, but when deployed onto a live terminal, refunds no longer work. DejaPay also doesn't throw any errors for refunds when running on an Engineering Mode terminal, so we had no help from it to see what was going on.
What we did find, however, is that we were missing some parameters in the request to refund/void, as per this document
What I did in order to fix this is to simply add the missing params and run a bunch of transactions and verify they still refund/void

Mob 1074 void payment

---

app/src/main/java/com/staxpayments/sample/ui/screens/MainScreen.kt
app/src/main/java/com/staxpayments/sample/viewmodel/StaxViewModel.kt
cardpresent/src/main/java/com/fattmerchant/android/Omni.kt
cardpresent/src/main/java/com/fattmerchant/android/chipdna/ChipDnaDriver.kt
cardpresent/src/main/java/com/fattmerchant/omni/AccessoryHelper.kt
cardpresent/src/main/java/com/fattmerchant/omni/Omni.kt
cardpresent/src/main/java/com/fattmerchant/omni/UsbAccessoryListener.kt

* Add simple `AccessoryHelper` and `UsbAccessoryListener` for emitting events when an ID Tech device is connected
* Add logging to sample app for when the accessory is connected
* Remove BT connection type and solely use BLE

[PHO-3699] Add USB Listener & Update BT Connection Type
